name: Run test cases

on: [push] # Or other events as needed

jobs:
  build:
    runs-on: ubuntu-latest # Or your preferred runner

    strategy:
      matrix:
        java-version: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v4 # Check out the code

      - name: Set up JDK 8 and 11 # Or your desired JDK version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # Or your preferred distribution

      - name: Compile and run with and without hashcode implementations
        run: |
          mkdir -p classes
          javac -d "./classes" src/org/knights/sequence/*
          java -cp "./classes" org.knights.sequence.Main 1 10
          java -cp "./classes" org.knights.sequence.Main 1 12
          java -cp "./classes" org.knights.sequence.Main 2 26
          java -cp "./classes" org.knights.sequence.Main 2 28
          java -cp "./classes" org.knights.sequence.Main 2 32
