name: Run Java Main Method

on: [push] # Or other events as needed

jobs:
  build:
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - uses: actions/checkout@v4 # Check out the code

      - name: Set up JDK 8 # Or your desired JDK version
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin' # Or your preferred distribution

      - name: Run Java Main Method
        run: |
          mkdir -p classes/production/knights-sequence
          javac -d "./classes/production/knights-sequence" src/org/knights/sequence/*
          java -classpath "./classes/production/knights-sequence" org.knights.sequence.Main 1 10
          java -classpath "./classes/production/knights-sequence" org.knights.sequence.Main 2 20
          java -classpath "./classes/production/knights-sequence" org.knights.sequence.Main 2 26
          java -classpath "./classes/production/knights-sequence" org.knights.sequence.Main 2 28
          java -classpath "./classes/production/knights-sequence" org.knights.sequence.Main 2 32
